# Generated by Django 5.2.6 on 2025-10-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_category_post_status_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
