# Generated by Django 5.2.6 on 2025-10-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_pub_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('education', 'Education'), ('legal', 'Legal Rights'), ('success', 'Success Stories'), ('awareness', 'Awareness'), ('activism', 'Activism')], max_length=50, null=True),
        ),
    ]
